project_id = "rwhgqhzvheoubqyuqwhq"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.msg91-webhook]
verify_jwt = false

[functions.parse-whatsapp-message]
verify_jwt = false

[functions.send-lead-notification]
verify_jwt = false